In [1]:
import numpy as np

In [2]:
nums = np.array([1, 2, 3, 4])
print(nums)

[1 2 3 4]


In [5]:
nums2 = nums.reshape(2, 2)
print(nums2)

[[1 2]
 [3 4]]


In [11]:
nums3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
print(nums3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
nums4 = np.reshape(2, 6)
print(num4)

ValueError: cannot reshape array of size 1 into shape (6,)